language: node_js
node_js:
- 10
before_script:
- npm install -g gulp-cli gulp@4
script:
- gulp
- npm run coverage
cache:
  directories:
  - node_modules
env:
  global:
    secure: OnKYvtw3fRQZ3fUlOKlTwwY1uDSypkzSmW0r2Rfs4plZqPkwCRI95ruRB1oMGt6vcBFwmun4e5Eju+i4QaB/MhJhumnbf+N3ywpCFD5pfamWmeKxKIsuZF9bVpzMTKXZrKFJbYZRw41phm6fSxnY5GG9rkeU4KRpwnIT6agySSrxP0XmWpFwhxTmXdkBl4i7KIau/rS0ru1HbC/XKY+X1zmz6Meps/NLTYzH0KH+RXcdNQupk8RL9p7buGZ6/Pw3lbMab/x6PWyuq253u1SV6P+w+nWo6HgafWlm0ipK2JrzBVyxAy4uz06ViSXX+YsJPBv6pW2N0rFJxmIU4vbvnV64I+E9f4hnfU5LbdX4l5QIQWzcW/rM6FXDIcosHiJXh10W81XEASw376GuBtF0pw0OsxCG9vdGhOkFgjXjGsefD6q6vRvDxauheJ7lrleZ1COL0oDjGjQtCZo56AbMAbAfjIZtV5X3sqdAXlKJqSsl9juz8waZxRpULjeVc/poE7c9KJ1xai/ry5GofMww39F+J4aO8+qEIyriLrGb8JJwIoDw2+hj+ufiZz4nzXQCWEWLK7Wy2/D7V+v5t5/KikFIq8g3txjroeJk/1Bu0IXSy6XFwSKd83V8UWgOLVU2lUCVcfksYG24zsecu45dretuR9GlEaJcEzYlrErduD4=
notifications:
  slack:
    secure: Mdj9/ZPoydbqk/5x+r08JkUtOCjCTPWvpSMpBH6aZXlFIl6kbCPObKzCz+vaGu9nKv4LcReJwwFYDIphF9looXPjstsJIrBUyzaFEbUg3U8CD3t4o/E2/kqANRWwOjP/i0nrKzx0h+15bzpiqjW8o/NQ48ItbCfp7wrqi8i+koa1s+CmdPLYcDbW+TqS5tKcoSWDn/SbqO+B4XNZNh9B8eXyp4wY/dpYWG+7yzVbSgT5kc82pXpIXRbxlESzhNlKcjM2dweSxBpt4hKOyxYp6ycDjj4HWjJQNIon6EzgGuiwwCvxrorknKyptj7jP/P/2H+DOCEfGW20CAxmLj3am8h/fqXAU7wSITG5aIF1kV9WRD9Amc0rsz2cpuuOXq57fY8NcQAt9QaMCd9xXUDh/tA4JQT9JWcAFgUHW9INfHrf+gt0/GvEbxskhFesftGT0aRohVHnSNStFgfKAcQRrbfBYdDr0DK6nzMLoDnaIKwsUmlisNnZVhtD9D13iGR7C8OS6+ICOp/FhApOKSGs7QylqgzblqxE9k9VZH4eZ0h1NUnKRfjaotERNHwRXpprtrXTCCjVomjhcY+3Uy8J1SPS73SSoSnjfofXuWp5Xl0IKkELj6wpUoT2b6QZViWCQ/4PL7tBGkcXZFoK/6P0X/fcUutWiN5lYZnEmzGs4YY=
deploy:
- provider: npm
  api_key:
    secure: C9Dc0wJzdnkkga25Ak9I4tP0kF0vu7JD9aegH7ZcdyCVd6honxkfSWCekOQyt3TyzT57tDZ8G+jL5LZZ9uKJBlVbbn3MIXTOE3KYJMVQGP0JHcbjJmW+AnhWkUGHtatEPI1JU0X5YIe62SJjZuW1lvz0IYaKQhq7lbV8DFDydMKrf0Oi5Np6ZddfhIB3iTM0qGVT441f9TJK+/N+zepP0DT9xFTpQTi2X3HN9vKrZ3Yd60dhAkLhg9L01fFnZg7vCej2t+C+t5LkiaA7WJ0IraRKgbRZrxp+cQ4t3TCVClMbnIEZJieiNJCBi4/MMTPhQLcFnu17VGpavFJJtJjFP9eVtrlpA577bv2cfsLRNmksPQXfxIsIjiSKCDYyMq/zYZSBznisVnanxQPmlZ4Abqt/rUhlck83W48lmVkXw45QaaOaSFYgxFDiSlSndQz7rteNR2YO78BwewdGrtCL3DCD1p+IHjZ1+8YyD5VZ86F9Am0iIdbhCPWEXD9RrlCQe0+F+lMC8kJIEh3hzyz/YMqrTI1pc4bPIBwQKfxSBOMgK0DKhhgP8EJgR7AMBLYE3y8qQqD7msWZ37DGhZjCHjd72uSgjMVsZ7VmHLvarnO6lekYrLjbS/mqg0QiDQPtKwzrvBHQ608EXXkuhYS13SNxp2ta7ts6y0mfKrqAnww=
  email:
    secure: kK/dn5YcrOt+mpvMFBZCM4Ptpgg5UaHxozFNQx9932JvdcCjiEDgEl1uHvTlUr1AHXmsmfGmc3LuXmO1S9Jhx4O8Yz+ewUIR+qHVBxicYzp9bZ5ut8J4A9fqH1nEqU/8j30++vV4/cBGYSzFsKFXCgV1mKs+8BdcWT5Ys+laKiMaEWA9g9M2eW++VPg9ovuAjB46zuJdS4du1iSAwu0PJgtEQR4ZrArvUENcDNjgOkJe5zaWNOuqqfHYLZTDzGCiuLdnjGJsffEh6mKQSzjKmJSK88qorkdnkKpGOwFK4mDUX0/h7ym4ibX9l5UrfGMz2jEjYZnfXKur6KHPqsf9py24r0piG53PoxwxUfjhxhBFrkGUu8MBrOFstoHxhz43VQ6iR4L/WxNhtc0/g8uBNfi8ZlS2F5c9ITIjzWvkSh30MCdb/+va7kryWAKZeys9UMueP7QlPCQ3Rpf7ReeC8PE3pYngla+gV9triCAo652v7eUdxd0M52IoJ9GEjvq9GtK3D6BmCcABFnHEAwpU7SMsS/UsTVQjZVsvnBWtorkgWxWAG6A6C7phfIQUZx+1q2qQvNfmSdU4xQF7vy4hfoeklQzwY6BkI+ZJSygAdNb0Xp50v4sJEbJG2E/tXIKPjiIJ3GXMBff5MUaMvw0QUxEJVyXeEwi0ELDHfsALJng=
  on:
    branch: master
