language: node_js
node_js:
- node
before_script:
- npm install -g gulp-cli
script:
- gulp
- npm run coverage
cache:
  directories:
  - node_modules
env:
  global:
    secure: EiBYRHWqJQAZVUnov7UA4+0Gb2eWEI8q1uk8JTI4MGk3wVwW0t/sIO9dE5k/pFdUCfH6M8wCcEwlGp4DgDjCiNjaJNySfsOUor7Km9YNCGcsqj+Phb6JoQ4dduuDs8HaIU5iKZEOh/ryY/+siAV96bUcIC1n7Aev3Nt8iAQl/3zyIS5sT5JSIJCAAGi7vMhAUMeV3BpVVf9WASh58dwIqfmyT5RsG/VrK3JVwtpTj/2F93T0fYw0ewl1g+qhEDbgTCtrgOK5fTKt7dEyAaDxxrTWCGsThJPD+ozfQ8pxnTpgd4PQKOR3kgu+Kgp1o524GG9pNBfNq/D+9aeTEV9czR1GtWFEsRgnbKZ1+7RufICRUvBcKh+PeHoz+GjqilpxUnKwjdYVKAN060TIWl9AhjF5WEtxNX9v7bcChBv1dL4KFLFx2VazW15MEPtY4MwQPh1DtXT6VwV8nky0KDakIw+Sv8690Oahj3KxRGqSvjZCj8lt5I/yjT1KrFq0sqeqojeDFFVrampQj1qyTpsZ7zf3XXK4bi4OdFCll5ZQ/WpY4W9rWZ3YA3QCxUcroR3LAWRAAGXEb8m6TztejdYbM/OzUNMlMgYNSx0MtwShXFUtHwz2iE/RenYccSzdVZdg+hks/kjT/JV3X3gBWMzBjVBs0EoenujcsxZ+i7CEKOg=
